# Configuration for running Dtangle in Step08
# Variables that need to be defined are:
#   normalization - list with any combination of 'counts', 'cpm', 'tmm',
#                   'tpm', 'log_cpm', 'log_tmm', or 'log_tpm', depending on
#                   which scale the algorithm expects values to be on and what
#                   it makes sense to run with the algorithm
#   reference_input_type - what type of data is used as the reference. Can be
#                   any of 'signature', 'singlecell', or 'pseudobulk'
#   marker_function - the name of the function to call to generate a
#                   marker-related parameter matrix. Options are either
#                   'CreateParams_MarkerTypes' or 'CreateParams_FilterableSignature'
#   params_markers - a named list of marker-related arguments to
#                   'CreateParams_FilterableSignature' or
#                   'CreateParams_MarkerTypes'. See those functions for input
#                   options. Any arguments not defined in the function call in
#                   this config file will be set to default values (see the
#                   functions for defaults). If all arguments should be left
#                   as default, this should be an empty list [].
#   additional_args - a matrix of combinations of algorithm-related arguments
#                   that are for the algorithm's function call. If the function
#                   doesn't need other arguments or you don't want to test
#                   them, this value should be an empty list [].
#   inner_loop_file - which file defines the algorithm-specific inner loop function
#   inner_loop_func - a string, the name of the inner loop function to call
#   required_libraries - a list of libraries needed for execution of the
#                    inner loop function, which is usually just the algorithm's
#                    library
#   ct_ad_only - true or false, whether to run Control and AD samples only, or
#                run all bulk samples.
#   cores - an integer value of how many CPUs to use when running in parallel.
#           For Dtangle, as many cores as will fit in RAM. Assume between 5-20 GB
#           of RAM needed per core, depending on the dataset.
default:
  # Used to create params_loop1 (data-specific arguments) in main function
  reference_input_type: "pseudobulk"
  normalization: ["log_cpm", "log_tmm", "log_tpm"] # Dtangle works on log-scale data

  # For params_loop2 (algorithm-specific arguments) in main function
  marker_function: "CreateParams_MarkerTypes"
  params_markers: [] # all args are default
  additional_args: [] # dtangle has additional arguments but we aren't testing them

  # Define the function that runs each param set
  inner_loop_file: !expr file.path("functions", "Step08_DtangleHSPE_InnerLoop.R")
  inner_loop_func: "DtangleHSPE_InnerLoop" # must be a string

  # How many cores to use in parallel
  cores: !expr parallel::detectCores() - 1 # Machine this was set up for has 16 cores
