default:
  # Used to create params_loop1 (data-specific arguments) in main function
  reference_input_type: "singlecell"
  normalization: ["counts", "counts_tpm"] # MuSiC works on linear-scale data

  # For params_loop2 (algorithm-specific arguments) in main function.
  # MuSiC was designed to use the whole set of genes, but I am testing whether
  # narrowing the gene set helps. Although MuSiC inputs singlecell/pseudobulk
  # data directly and not a signature, calling this function is the easiest
  # way to get the genes to use both for the whole gene set and for a subset
  # of markers.
  marker_function: "CreateParams_FilterableSignature"
  params_markers:
    filter_level: [0, 1, 2, 3]
    n_markers: [3, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000]
  additional_args:
    centered: [true, false]
    normalize: [true, false]

  # Define the function that runs each param set
  inner_loop_file: !expr file.path("functions", "Step08_Music_InnerLoop.R")
  inner_loop_func: "Music_InnerLoop" # must be a string

  # How many cores to use in parallel -- Music multi-threads a little bit and
  # requires a lot of memory. cores/2 works for broad class but needs to be
  # reduced to ~ cores/3 for sub class.
  cores: !expr round(parallel::detectCores() / 2)
